hitobito/hitobito_youth

- app/helpers/group_educations_helper.rb
- spec/helpers/group_educations_helper_spec.rb
[#107](https://github.com/hitobito/hitobito/issues/107)
> Add expiration date to qualifications

- app/domain/export/tabular/people/participation_ndbjs_row.rb
- app/domain/export/tabular/people/participations_sportdb.rb
- spec/domain/export/tabular/people/participation_sportdb_row_spec.rb
> Fixes #779

- app/views/event/lists/_popover_bsv_export.html.haml
- app/views/event/participations/_popover_cancel.html.haml
- app/views/event/tentatives/new.html.haml
This change is introduced by hitobito/hitobito#870, and should only be merged together with that PR.
> Rename save_form_buttons to form_buttons

- app/helpers/youth/dropdown/event/participant_add.rb
- app/views/event/participations/_actions_show_youth.html.haml
> Migrate FontAwesome to version 5

- app/models/youth/person.rb
- config/locales/models.youth.de.yml
- config/locales/models.youth.fr.yml
- config/locales/models.youth.it.yml
- hitobito_youth.gemspec
- spec/domain/export/tabular/people/participation_ndbjs_row_spec.rb
- spec/domain/export/tabular/people/participation_sportdb_row_spec.rb
- spec/jobs/export/event_participations_export_job_spec.rb
- spec/models/person_spec.rb
Merge after https://github.com/hitobito/hitobito_pbs/pull/147
> Move ahv number pattern check from hitobito_pbs to hitobito_youth and add checksum validation

- spec/domain/export/tabular/people/participation_ndbjs_row_spec.rb
- spec/jobs/export/event_participations_export_job_spec.rb
Flick für die Tests, welche durch https://github.com/hitobito/hitobito/pull/922 kaputt gemacht wurden.
> Fix tests broken by phone number validation introduced in hitobito core

- config/locales/models.youth.de.yml
- config/locales/models.youth.fr.yml
- config/locales/models.youth.it.yml
Issue: hitobito/hitobito#946
Im Zusammenhang mit Core-PR: hitobito/hitobito#1081
Die englische Übersetzung werde ich noch im Transifex einpflegen.
> Sharpen event particip. additional info label

- app/controllers/event/tentatives_controller.rb
- bin/rspec
- spec/fixtures/event/question_translations.yml
- spec/fixtures/event/questions.yml
- spec/fixtures/event_translations.yml
- spec/fixtures/events.yml
Can and should be merged once https://github.com/hitobito/hitobito/pull/1135 is merged.
> Translate events

- .github/workflows/tests.yml
Issue: https://github.com/hitobito/hitobito/issues/1190
> ci: add github action

- app/controllers/youth/event/lists_controller.rb
- lib/hitobito_youth/wagon.rb
- spec/controllers/event/lists_controller_spec.rb
While changing to GH-Actions, I noticed a spec-failure that could be remedied by using the new filters. I propose this change as a Pull-Request in case it interferes with a solution for hitobito/hitobito#1153.
> Repair specs

- app/views/events/courses/_popover_bsv_export.html.haml
- spec/controllers/event/lists_controller_spec.rb
Merge together with hitobito/hitobito#1352
> Adjust BSV export to course filter improvements

- lib/hitobito_youth/wagon.rb
Merge together with hitobito/hitobito#1695
> Adapt to core changes in table displays config

- app/decorators/youth/person_decorator.rb
- app/models/youth/person.rb
- app/views/event/participation_contact_datas/_fields_youth.html.haml
- app/views/people/_details_youth.html.haml
- app/views/people/_fields_youth.html.haml
- config/locales/models.youth.de.yml
- config/locales/models.youth.fr.yml
- config/locales/models.youth.it.yml
- config/locales/views.youth.de.yml
- config/locales/views.youth.fr.yml
- config/locales/views.youth.it.yml
- db/migrate/20230126155336_migrate_nationality_to_new_nds.rb
- lib/hitobito_youth/wagon.rb
- spec/domain/export/tabular/people/participation_nds_row_spec.rb
- spec/migrations/migrate_nationality_to_new_nds_spec.rb
- spec/models/person_spec.rb
Closes: https://github.com/hitobito/hitobito/issues/1961
> Migrate nationality_j_s for NDS

- app/abilities/youth/person_ability.rb
- app/abilities/youth/person_layer_writables.rb
- app/abilities/youth/person_readables.rb
- app/controllers/youth/people_controller.rb
- app/views/people/_details_youth.html.haml
- app/views/people/_fields_youth.html.haml
- app/views/people/manageds/_fields.html.haml
- config/locales/models.youth.de.yml
- config/locales/views.youth.de.yml
- config/settings.yml
- lib/hitobito_youth/wagon.rb
- spec/abilities/person_ability_spec.rb
- spec/features/people_manager_relation_spec.rb
Fixes hitobito/hitobito#1966
Fixes hitobito/hitobito#2020
Merge together with these wagon PRs:
hitobito/hitobito_pbs#255
hitobito/hitobito_cevi#105
hitobito/hitobito_jubla#43
> Elternzugang 1-2

- app/views/event/register/_manager_fields.html.haml
> Allow to control the persons used_attributes

- app/helpers/group_educations_helper.rb
- spec/helpers/group_educations_helper_spec.rb
Fixes: https://github.com/hitobito/hitobito/issues/2234
> Make educations columns html safe after sanitizing qualification kind label

- app/domain/youth/people/cleanup_finder.rb
- lib/hitobito_youth/wagon.rb
- spec/domain/people/cleanup_finder_spec.rb
Refs: https://github.com/hitobito/hitobito/issues/2106
Requires: https://github.com/hitobito/hitobito/pull/2229
> Add cleanup finder adjustments

- app/domain/youth/mail_relay/address_list.rb
- spec/domain/mail_relay/address_list_spec.rb
- spec/fixtures/people.yml
- spec/fixtures/people_managers.yml
- spec/fixtures/roles.yml
fixes hitobito/hitobito_sac_cas#401
> Fix MailRelay::AddressList#entries when called for new records

- app/controllers/youth/event/participation_contact_datas_controller.rb
- spec/features/event_register_managed_spec.rb
Fixes: https://github.com/hitobito/hitobito/issues/2502
> Use correct privacy policy param for registering managed to event

- app/models/youth/event/course.rb
- spec/models/event/course_spec.rb
refs hitobito/hitobito_sac_cas#318
> Show qualified in person history events

- app/helpers/event/participation_buttons.rb
- app/helpers/event_participation_youth_helper.rb
- app/views/event/participations/_actions_show_youth.html.haml
- spec/controllers/event/participations_controller_spec.rb
- spec/helpers/event/participation_buttons_spec.rb
refs hitobito/hitobito_sac_cas#369
> Extract participations show actions into PORO

- app/views/events/courses/_popover_bsv_export.html.haml
> Un-turbo-ize the BSV-Export

- app/helpers/event/participation_buttons.rb
- app/views/event/participations/_popover_cancel.html.haml
- app/views/events/_actions_show_youth.html.haml
refs hitobito/hitobito_sac_cas#375
> Add render_extensions to participations/_popover_cancel partial

- app/views/event/register/register.html.haml
refs hitobito/hitobito#2577
refs hitobito/hitobito_sac_cas#246
> Adapt for extracted fields partial in core

- app/helpers/youth/dropdown/people_export.rb
- lib/hitobito_youth/wagon.rb
- spec/helpers/dropdown/people_export_spec.rb
Method now returns item. This allows adding to the menu in subclass.
fixes hitobito/hitobito_sac_cas#427
> Dropdown::PeopleExport#tabular_links: refactor to match return value of core

- app/controllers/event/participation_contact_data/managed_controller.rb
- app/controllers/event/tentatives_controller.rb
- app/controllers/people_managers_controller.rb
- app/views/person/manageds/_new_person_fields.html.haml
> Add missing unprocessable_entity status codes

- app/abilities/youth/person_readables.rb
Refs hitobito/hitobito_sac_cas#384
> Avoid expensive joins

- app/domain/export/tabular/people/participation_nds_row.rb
- app/domain/export/tabular/people/participations_nds_camp.rb
- app/domain/export/tabular/people/participations_nds_course.rb
- spec/domain/export/tabular/people/participation_nds_camp_spec.rb
- spec/domain/export/tabular/people/participation_nds_row_spec.rb
- spec/features/external_event_register_manager_spec.rb
- spec/fixtures/people.yml
- spec/jobs/export/event_participations_export_job_spec.rb
- spec/spec_helper.rb
> Adapt to changed columns

- app/controllers/people_managers_controller.rb
- app/models/people_manager.rb
- app/models/youth/person.rb
- app/views/person/manageds/new.html.haml
- config/locales/models.youth.de.yml
- spec/features/people_managers_spec.rb
> Run person validations on people_manager create

- app/views/people/_people_managers_aside.html.haml
- app/views/people/_show_right_youth.html.haml
This allows customizing the people manager aside in depending wagon. 
Fixes hitobito/hitobito_sac_cas#712
> Extract _people_managers_aside to its own partial

- CHANGELOG.md
- app/domain/ahv_number_validator.rb
- app/domain/export/tabular/people/participation_nds_row.rb
- app/models/event/question/ahv_number.rb
- app/models/youth/person.rb
- db/seeds/event_questions.rb
- spec/domain/export/tabular/people/participation_nds_row_spec.rb
- spec/domain/synchronize/mailchimp/subscriber_spec.rb
- spec/features/question_spec.rb
- spec/fixtures/event/questions.yml
- spec/models/event/question/ahv_number_spec.rb
- spec/models/person_spec.rb
> feat: add default ahv question for #58

- db/seeds/event_questions.rb
Gehört zu https://github.com/hitobito/hitobito/pull/2847
> fix: prevent global questions from being seeded multiple times

- app/views/event/questions/event_question_ahv_number/_fields.html.haml
Muss mit  https://github.com/hitobito/hitobito/pull/2877 gemerged werden
> fix: refactor question fields to reflect sti (hitobito_youth#58)

- app/controllers/youth/event/lists_controller.rb
- spec/domain/people/cleanup_finder_spec.rb
> Add explicit #start_on/#end_on to Role, remove FutureRole, Role#delete_on

- CHANGELOG.md
> fix: add changelog for existing changes (hitobito_youth#85)

- app/helpers/event/participation_buttons.rb
hitobito/hitobito_sac_cas#1389
> Support passing options when building participation_buttons

- spec/fixtures/groups.yml
fixes hitobito/hitobito_sac_cas#1488
> Fix specs to heed newly introduced validation of foreign zips

- spec/jobs/export/event_participations_export_job_spec.rb
fixes hitobito/hitobito_sac_cas#1512
> Fix spec after method signature change in core (hitobito/hitobito_sac_cas#1512)

- spec/features/event_register_managed_spec.rb
> Extend list of mocked FeatureGates

- app/controllers/youth/event/participations_controller.rb
- spec/controllers/event/participations_controller_spec.rb
Refs: https://github.com/hitobito/hitobito_sac_cas/issues/1843
> Refresh participant count for event on participation cancel

- app/jobs/youth/export/event_participations_export_job.rb
> Use the new index_full_participations ability
